language: node_js
node_js:
  - '8'
env:
  global:
    - REACT_APP_API_URL="https://charlotteapp-api.herokuapp.com"
branches:
  only:
    - master
script:
  - yarn test:coverage
deploy:
  provider: heroku
  api_key: "$HEROKU_APP_ID"
  app: "$HEROKU_APP_APP_NAME"
cache:
  yarn: true
  directories:
    - "node_modules"
